### PR TITLE
Add support for TARGET_OS_MACCATALYST

### PR DESCRIPTION
**Pull request by olilarkin**

### CODE REVIEW

**Comment by olliwang** [comment]
What's the bitcode included for catalyst?

**Comment by olilarkin** [comment]
how could I check?

**Comment by olliwang** [comment]
`nanovg_mtl.m` includes a bitcode header as below. Which is included when `TARGET_OS_MACCATALYST` is defined? Please make sure a valid one is included.

```
#if TARGET_OS_SIMULATOR
#  include "mnvg_bitcode/simulator.h"
#elif TARGET_OS_IOS
#  include "mnvg_bitcode/ios.h"
#elif TARGET_OS_OSX
#  include "mnvg_bitcode/macos.h"
#elif TARGET_OS_TV
#  include "mnvg_bitcode/tvos.h"
#else
#  define MNVG_INVALID_TARGET
#endif
```

**Comment by olilarkin** [comment]
"mnvg_bitcode/ios.h" gets included

**Comment by olliwang** [comment]
That's great. Thanks. 👍🏼

**Pull request merged**
